// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package html

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Blog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"content\"><!-- Blog Header / Intro Section --><section class=\"blog-intro\"><h2>Blog</h2><p>Welcome to my blog! Here you’ll find articles on web development, design tips, and personal insights.</p></section><!-- Blog Posts Section --><section class=\"blog-posts\"><article class=\"blog-post\"><h3>Understanding CSS Grid</h3><p class=\"post-date\">Published on October 1, 2025</p><p>CSS Grid is a powerful layout system available in CSS. In this post, we'll explore the basics of rows, columns, and how to create responsive designs.</p><a href=\"#\" class=\"read-more\">Read More</a></article><article class=\"blog-post\"><h3>Improving Web Performance</h3><p class=\"post-date\">Published on September 15, 2025</p><p>Optimizing your website’s performance is crucial. We’ll dive into image compression, code splitting, caching strategies, and more.</p><a href=\"#\" class=\"read-more\">Read More</a></article><!-- Add as many posts as you want --></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
