// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package html

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Contact() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"content\"><!-- Contact Intro Section --><section class=\"contact-intro\"><h2>Contact</h2><p>Have a question, want to work together, or just want to say hi? Feel free to reach out using the form below or via email.</p></section><!-- Contact Form Section --><section class=\"contact-form\"><form action=\"#\" method=\"POST\"><div class=\"form-group\"><label for=\"name\">Name</label> <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Your Name\" required></div><div class=\"form-group\"><label for=\"email\">Email</label> <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Your Email\" required></div><div class=\"form-group\"><label for=\"message\">Message</label> <textarea id=\"message\" name=\"message\" rows=\"5\" placeholder=\"Your Message\" required></textarea></div><button type=\"submit\">Send Message</button></form></section><!-- Additional Contact Info Section --><section class=\"contact-info\"><h3>Other Ways to Connect</h3><ul><li>Email: <a href=\"mailto:hello@example.com\">hello@example.com</a></li><li>LinkedIn: <a href=\"https://linkedin.com/in/yourprofile\">/in/yourprofile</a></li></ul></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
