services:
  go_app:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: go_app
    restart: unless-stopped
    networks:
      - app_network
    expose:
      - 8000 #Documentation purpose only

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx 
    restart: unless-stopped
    networks:
      - app_network
    expose:
      - 80 # Documentation purpose only 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - go_app

networks:
  app_network:
    driver: bridge
