// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><div class=\"introduction\"><h2>Hi, I'm vphatfla!</h2><p>My username is a combination of my name and the state I immigrated to in the US not long ago. </p></div><div class=\"introduction\"><p>I am a rising senior at the University of Central Florida. I love writing code and learning the fundamental of Computer Science.  I strive for simplicity, reliability, and performance in my code. </p></div><div class=\"experience\"><h2>Where I have been to</h2><ul><li><strong>University of Central Florida</strong> Electrical Grid System. Architecture and application of AI in Inverted Based Resource devices</li><li><strong>Apple</strong> Distributed Trading - Observability Tooling for distributed system</li><li><strong>Leidos</strong> Autonomous Application - serverless Microsoft document automation application</li><li><strong>JP Morgan Chase</strong> Enterprise Reporting Data - Batch Ingestion and Provisioning applications</li></ul></div><div class=\"quote\"><h2>My favorite quote</h2><p>\"Start with the customer experience, then work back to the technology.\"</p><p>- Steve Job</p></div><div class=\"stack\"><p>This site is build with htmx, sass, go, templ. I enjoy the simplicity of this stack. </p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
