//Generated by build-docs.js
import Contact from '@/pages/generated/Contact.vue'
import Home from '@/pages/generated/Home.vue'
import Work from '@/pages/generated/Work.vue'
import BuildingModernStaticSites from '@/pages/generated/blog/BuildingModernStaticSites.vue'
import OptimizingWebPerformance from '@/pages/generated/blog/OptimizingWebPerformance.vue'
import BlogIndex from '@/pages/generated/BlogIndex.vue'

export const routes = [
{
    path: '/',
    component: Home,
},
{
    path: '/blog',
    component: BlogIndex,
},
{
    path: '/contact',
    component: Contact,
},
{
    path: '/work',
    component: Work,
},
{
    path: '/blog/buildingmodernstaticsites',
    component: BuildingModernStaticSites,
},
{
    path: '/blog/optimizingwebperformance',
    component: OptimizingWebPerformance,
}
]