//Generated by build-docs.js
import Contact from './components/generated/Contact.vue'
import Home from './components/generated/Home.vue'
import BuildingModernStaticSites from './components/generated/blog/BuildingModernStaticSites.vue'
import OptimizingWebPerformance from './components/generated/blog/OptimizingWebPerformance.vue'
import BlogIndex from './components/generated/BlogIndex.vue'

export const routes = [
{
    path: '/',
    component: Home,
},
{
    path: '/blog',
    component: BlogIndex,
},
{
    path: '/contact',
    component: Contact,
},
{
    path: '/home',
    component: Home,
},
{
    path: '/blog/buildingmodernstaticsites',
    component: BuildingModernStaticSites,
},
{
    path: '/blog/optimizingwebperformance',
    component: OptimizingWebPerformance,
}
]