//Generated by build-docs.js
import Contact from '@/pages/generated/Contact.vue'
import Home from '@/pages/generated/Home.vue'
import Work from '@/pages/generated/Work.vue'
import YouHaveTime from '@/pages/generated/blog/YouHaveTime.vue'
import BlogIndex from '@/pages/generated/BlogIndex.vue'

export const routes = [
{
    path: '/',
    component: Home,
},
{
    path: '/blog',
    component: BlogIndex,
},
{
    path: '/contact',
    component: Contact,
},
{
    path: '/home',
    component: Home,
},
{
    path: '/work',
    component: Work,
},
{
    path: '/blog/youhavetime',
    component: YouHaveTime,
}
]