name: GO Backend CI

on:
  push:
    paths:
      - 'back-end/**'
    branches:
      - main
  pull_request:
    paths:
      - 'back-end/**'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Build
      run: |
       cd back-end
       go build ./...

    - name: Test
      run: |
        cd back-end
        cd test 
        go test .  
