name: Backend CD - Deploy to EC2

on:
  push:
    paths:
      - 'back-end/**'
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs: 
  backend-cd:
    name: backend-cd-deploy-to-ec2 
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["cd ~/oppy-marser || exit 1","git pull origin main || exit 1", "cd back-end || exit 1", "docker-compose down || exit 1", "docker-compose up --build -d || exit 1"]}' \
            --output text
