name: GO Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4

    - name: Set up GO
      uses: action/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Build
      run:
       cd back-end
       go build ./...

    - name: Test
      run:
        cd back-end
        cd test 
        go test .  
