name: Node NPM Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       
       - name: Set up Node
         uses: actions/setup-node@v4
         with:
           node-version: '20.16'
       - name: Install NPM Packages
         run: |
          cd front-end     
          npm ci 
       - name: Build Static Files 
         run: |
          cd front-end 
          npm run build
       - name: Run NPM Test
         run: |
          cd front-end
          npm test
